name: Release
on:
  push:
    branches: [master]
jobs:
  release:
    uses: cloudnationhq/terraform-azure-workflows/.github/workflows/release-please.yml@main
    permissions:
      contents: write
      pull-requests: write
